### ISSUE TITLE
[Feature Request] Please add a chart to show status like AniList in the Home page.

### ISSUE THREAD

**Issue by Mornwind** [NicoAiko/zerotwo#102]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, just a suggestion while browsing.

**Describe the solution you'd like**
Add a chart at the right side of the avatar in the Home, which could show the whole status of watching/reading like AniList.
Please have a look at the attachments.

**Describe alternatives you've considered**
Nothing.

**Additional context**
![IMG_6026](https://user-images.githubusercontent.com/38060040/64175289-92cb0500-ce8d-11e9-8123-f61c36ca096a.jpeg)
![IMG_6028](https://user-images.githubusercontent.com/38060040/64175308-9a8aa980-ce8d-11e9-9420-a935ca04088a.jpeg)

**Comment by NicoAiko** [comment]
Well, the area you marked as "so empty here" actually isn't empty space but is used for your profile banner. As you don't seem to have set one, it's "empty space". I recommend you adding a banner image you like :)

As for the chart idea, yes. I thought of something similar to add.
It's definitely a nice touch that shouldn't be ignored.

**Comment by Mornwind** [comment]
Or you can divide the Home page into several Tabs.😆

**Comment by NicoAiko** [comment]
01e67d657dcef0177ba540c298c080bfc9542a92
