### ISSUE TITLE
[Feature Request] Use Markdown file to show the Latest Update.

### ISSUE THREAD

**Issue by Mornwind** [NicoAiko/zerotwo#103]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. Just a suggestion.

**Describe the solution you'd like**
Use Markdown file to show the Latest Update, and use unordered list to list the contents, for Markdown is a good tool to show and edit these kind of contents.

**Describe alternatives you've considered**
Nothing

**Additional context**
![IMG_6027](https://user-images.githubusercontent.com/38060040/64175845-ca867c80-ce8e-11e9-950c-83c675a26d3f.jpeg)
![IMG_6029](https://user-images.githubusercontent.com/38060040/64175855-ceb29a00-ce8e-11e9-87a6-9df64e9cbf18.jpeg)

**Comment by NicoAiko** [comment]
I'll have to take a look on how to add the icons into the markdown file, but generally this is a very good idea, yes.

**Comment by NicoAiko** [comment]
Generally, this is a good idea, but as this would mean each update needs its own update file, I would rather update the current JSON structure to allow more complex items.
