### ISSUE TITLE
[Bug Report] Simplified Chinese’s font issue.

### ISSUE THREAD

**Issue by Mornwind** [NicoAiko/zerotwo#104]
**Describe the bug**
The font of SC shows normal at the beginning when open the site. But it will change to another font after few seconds which seems abnormal with some characters.

**To Reproduce**
1. Open zerotwo.org in a Browser.
2. Set the language to ”Simplified Chinese”.
3. Wait for the font changed by itself.

**Expected behavior**
Keep the font of SC not change by itself.

**Screenshots**
Before: The font seems well.
![IMG_5988](https://user-images.githubusercontent.com/38060040/64176480-1f76c280-ce90-11e9-9f50-5d77eaa45c60.png)

After: The font seems abnormal with some characters.
![IMG_5989](https://user-images.githubusercontent.com/38060040/64176482-21408600-ce90-11e9-9f24-ae6d673188ad.png)

**Smartphone (please complete the following information):**
 - Device: iPad Pro 3 (11-inch)
 - OS: iOS 13.1 beta
 - Browser Safari
 - Version (I don’t know the version of Safari)

**Additional context**
Nothing.

**Comment by NicoAiko** [comment]
It seems, either your cache is not yet refreshed or the CSS is acting weird.

Either way, I'll implement another idea which has to do with the language settings and fonts.

Languages will have special css classes that also contain certain certain fonts that it should load.

So when using the Chinese language, it shouldn't use Japanese fonts and vice-versa.

I'll work on this asap.

**Comment by Mornwind** [comment]
Glad to hear that. Thanks!
