### ISSUE TITLE
Spelling errors and translation mistakes in Italian locale

### ISSUE THREAD

**Issue by NicoAiko** [NicoAiko/zerotwo#141]
@Knocks83 

I might have found some little mistakes in the locale.

"watchedEpisode": "Visti {1} **of** {0}",
"rewatchedEpisode": "Rivisti {1} **of** {0}",
"readChapter": "Capitoli letti {1} **of** {0}",
"rereadChapter": "Capitoli riletti {1} **of** {0}",

Can you confirm?

**Comment by Knocks83** [comment]
Confirmed, I'll fix them right away
