### ISSUE TITLE
List doesn't change if I go to a empty list

### ISSUE THREAD

**Issue by Knocks83** [NicoAiko/zerotwo#142]
If you go to an empty list (to find this problem I actually emptied the paused list) you cannot change your list anymore, since everytime you choose a tab (watching, paused, dropped etc) it will still show you the first tab you watched (the one you were watching before the empty tab)

**To Reproduce**
Go in a empty list and try to switch list

**Expected behavior**
It should change tab

**Screenshots**
![1](https://user-images.githubusercontent.com/22529815/66270070-9fa59480-e84f-11e9-929b-b87283c08aad.png)
![2](https://user-images.githubusercontent.com/22529815/66270079-a7653900-e84f-11e9-9d79-69cf0e5dcf3a.png)
![3](https://user-images.githubusercontent.com/22529815/66270080-a92efc80-e84f-11e9-8575-605d858decfb.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.6.2-20190313b of Desktop Client (the latest precompiled version)

Edit: added exact version of the client

**Comment by NicoAiko** [comment]
This problem seems to only occur on the desktop version that is no longer supported.

I'd recommend you using either the web-app version or using Chrome's PWA compatibility to install ZeroTwo's latest version as PWA on your local machine.
