### ISSUE TITLE
Back button + Related animes

### ISSUE THREAD

**Issue by Knocks83** [NicoAiko/zerotwo#147]
**Is your feature request related to a problem? Please describe.**
I'll abuse of the template: I'm always frustrated when I open a anime from my completed anime and I cannot go bach one page without scrolling the whole page again
+
I'd love to have a related section in the anime description so I can find the source (manga/novel from which the anime is based) and the other seasons/OAVs

**Describe the solution you'd like**
Back Button
+
In the anime page, a new square with all the related anime (under the "information of your list" square)

**Comment by NicoAiko** [comment]
First part is a duplicate to #113 
The second part isn't, so I'll transfer that into a separate ticket and close this one marked as duplicate.
