### ISSUE TITLE
Add to list in Season Preview makes every button animate

### ISSUE THREAD

**Issue by Knocks83** [NicoAiko/zerotwo#148]
**Describe the bug**
When adding a anime from Season Preview to Watching list every button does the load animation

**To Reproduce**
1. Go to Season Preview
2. Press add to list

**Screenshots**
![image](https://user-images.githubusercontent.com/22529815/66487735-22775b00-eaad-11e9-8b51-a30a5be61ffc.png)

**Desktop:**
 - OS: Windows
 - Browser: Chrome PWA

**Comment by NicoAiko** [comment]
Confirmed, although right now low priority.
