### ISSUE TITLE
Status error for animes not in list

### ISSUE THREAD

**Issue by Knocks83** [NicoAiko/zerotwo#149]
**Describe the bug**
If a anime isn't in list it's shown as Planned

**To Reproduce**
1. Open a anime not in list

**Expected behavior**
It should be shown as not in list

**Screenshots**
![image](https://user-images.githubusercontent.com/22529815/66488313-032cfd80-eaae-11e9-92d2-1786ef832332.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome PWM

**Comment by NicoAiko** [comment]
I think there is a misunderstanding there.

The `Planning` is a default value that's taken if an item isn't in the list.

The subtitle shows `This media is not yet in your list` and the button on the button says `Add`.
