### ISSUE TITLE
Half episodes isn't half watched "circle"

### ISSUE THREAD

**Issue by Knocks83** [NicoAiko/zerotwo#164]
**Describe the bug**
If you set as watched half the episodes the episodes circle doesn't fill halfway.

**To Reproduce**
1. Set a anime to half the episodes

**Screenshots**
![image](https://user-images.githubusercontent.com/22529815/69493511-c8412680-0eaf-11ea-8db6-badeb7855c7f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome

**Comment by NicoAiko** [comment]
Hm, that's an interesting bug. I tried to reproduce this case but couldn't.
It's 50% for me.
I'll check other Browsers than Chrome, too.
![Bildschirmfoto 2019-12-11 um 08 48 27](https://user-images.githubusercontent.com/22343587/70601742-05692080-1bf3-11ea-8126-6a42e1383cae.png)

**Comment by NicoAiko** [comment]
Firefox also seems to be fine.
Can you tell me, how this came to be?
Did you update it and the percentage didn't change?

**Comment by Knocks83** [comment]
It probably was just a temporary bug, now it works fine to me too.
