### ISSUE TITLE
Gerne sorting/filtering

### ISSUE THREAD

**Issue by Kaiste232** [NicoAiko/zerotwo#29]
Ability to sort/filter the anime lists by gerne.

e.g. Selecting the gerne "Action" and only animes with the gerne "action" listed, on mal, show up.

**Comment by NicoAiko** [comment]
Okay, I have an update on this.

Probably, this feature is not coming with MyAnimeList support, but with AniList support.

Unfortunately, MyAnimeList is not that supportive to access their database.

On the contrary though, I can fully access AniList which by the way even allows importing your list from MyAnimeList with just one click and without the need of authenticating.

I’ll probably enhance this app more to the AniList side as it’s more open and easier to use.
