### ISSUE TITLE
Tags that are set on MAL aren't displayed

### ISSUE THREAD

**Issue by Kaiste232** [NicoAiko/zerotwo#33]
self explanatory

**Comment by NicoAiko** [comment]
Can you go into more detail? What kind of tags do you mean? @Kaiste232

**Comment by Kaiste232** [comment]
For example this anime list:
https://myanimelist.net/animelist/Captain220?status=2

You can see that he sets a lot of "tags".

**Comment by NicoAiko** [comment]
Ah, okay.

Would you say it **has** to be one of the main list's columns or is it an information that can be displayed in the information modal?

**Comment by Kaiste232** [comment]
I don't know. 

I don't use tags but I would guess that people use them to sort their animes as you can click on a tag and MAL displays only the ones with the same tag. I don't know if this is actually importanted. I just noticed it.

**Comment by NicoAiko** [comment]
I’ll consider it.

As of now, to me it doesn’t seem to be a critical issue. If more people (if they are really using this app) want this feature, I’ll probably implement it.

**Comment by NicoAiko** [comment]
MAL discontinued their external API.

Closing.
