### ISSUE TITLE
Sometimes the search doesn't function properly 

### ISSUE THREAD

**Issue by Kaiste232** [NicoAiko/zerotwo#36]
The video inside of the zip should explain the problem.

I enter "red" into the search bar and it shows no results. After deselecting and selecting the search again the results pop up.

[bug_zerotwo.zip](https://github.com/NicoAiko/zerotwo/files/1864769/bug_zerotwo.zip)

**Comment by NicoAiko** [comment]
Related to #35 as the search engine is behaving buggy.
