### ISSUE TITLE
watching list 

### ISSUE THREAD

**Issue by tom2411** [NicoAiko/zerotwo#82]
Hello
I wanted to tell you that when I log in anilist with your app, animes which was on "Watching" was those that are in "Rewatching".
So I don't know if it's me or a bug.

**Comment by NicoAiko** [comment]
Interesting bug. I haven't seen that one before. Maybe you want to join the Discord server and we can take a look at this problem together?

**Comment by NicoAiko** [comment]
This bug won't be fixed within 0.6.x versioning.

After the rewrite, this is fixed.
